# Generated by Django 5.2.5 on 2025-08-19 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
        ('connections', '0002_alter_connection_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='habitentry',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='circle',
            name='allow_public_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='circle',
            name='require_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='circle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='circlemembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='circles.circle'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='circle_type',
            field=models.CharField(choices=[('project', 'Project'), ('habit', 'Habit Building'), ('learning', 'Learning'), ('accountability', 'Accountability'), ('social', 'Social')], max_length=20),
        ),
        migrations.AlterField(
            model_name='circle',
            name='interests',
            field=models.ManyToManyField(blank=True, to='connections.interest'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='max_members',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='circlemembership',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='habitentry',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='circlemembership',
            unique_together={('user', 'circle')},
        ),
    ]
