# Generated by Django 5.2.5 on 2025-08-19 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='interest',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interest',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='connectionrequest',
            unique_together={('sender', 'receiver', 'request_type')},
        ),
    ]
