# Generated by Django 5.2.5 on 2025-08-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_widgets',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('connections', 'Connections Only'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='widget_preferences',
            field=models.JSONField(default=dict),
        ),
    ]
