# Generated by Django 5.2.5 on 2025-08-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_options_and_more'),
        ('users', '0003_profile_active_widgets_profile_profile_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='connections.interest'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_circles_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_habits_publicly',
            field=models.BooleanField(default=False),
        ),
    ]
